session_name: faster-ground-robot
windows:
  - window_name: ground-robot
    layout: tiled
    panes:
      - roscore
      - roslaunch --wait faster ground_robot.launch name:=JA01
      - roslaunch --wait global_mapper_ros global_mapper_node.launch quad:=JA01
      - roslaunch --wait faster faster_interface.launch quad:=JA01 is_ground_robot:=true
      - roslaunch --wait faster faster.launch quad:=JA01